import numpy as np
from scipy.spatial import ConvexHull

import torch
from .shape_tables import gridAngles, vertList, triTable


def calculate_mesh_features(mask_tensor, spacing):
    device = mask_tensor.device
    
    # Pre-load tables to CUDA if necessary
    triTable_t = torch.tensor(triTable, device=device, dtype=torch.int64)
    vertList_t = torch.tensor(vertList, device=device, dtype=torch.float32)
    gridAngles_t = torch.tensor(gridAngles, device=device, dtype=torch.int64)
    
    # Build a cube index for each non-edge voxel
    # Pad by 1 on all sides so boundary faces are fully captured by marching cubes
    padded_mask = torch.zeros(
        (mask_tensor.shape[0]+2, mask_tensor.shape[1]+2, mask_tensor.shape[2]+2), 
        dtype=torch.uint8, device=device
    )
    padded_mask[1:-1, 1:-1, 1:-1] = mask_tensor
    
    cube_idx = torch.zeros((mask_tensor.shape[0]+1, mask_tensor.shape[1]+1, mask_tensor.shape[2]+1), dtype=torch.uint8, device=device)
    for a_idx in range(8):
        c_z = gridAngles_t[a_idx][0]
        c_y = gridAngles_t[a_idx][1]
        c_x = gridAngles_t[a_idx][2]
        
        corner = padded_mask[
            c_z:c_z+mask_tensor.shape[0]+1,
            c_y:c_y+mask_tensor.shape[1]+1,
            c_x:c_x+mask_tensor.shape[2]+1
        ]
        cube_idx |= (corner << a_idx)
    
    valid_cubes = (cube_idx > 0) & (cube_idx < 255)
    active_indices = torch.nonzero(valid_cubes, as_tuple=True)
    active_idxs = cube_idx[active_indices]
    
    # Apply symmetry mask: if >= 128, flip bits and sign
    signs = torch.where(active_idxs >= 128, torch.tensor(-1.0, device=device), torch.tensor(1.0, device=device))
    lookup_idxs = torch.where(active_idxs >= 128, active_idxs ^ 255, active_idxs).long()
    
    tri_data = triTable_t[lookup_idxs]
    
    total_area = 0.0
    total_volume = 0.0
    all_vertices_list = []
    area_vector_sum = torch.zeros(3, device=device, dtype=torch.float64)
    
    spacing_t = torch.tensor(spacing, device=device, dtype=torch.float64)
    # The offsets are active indices [Z, Y, X]. They are relative to the padded mask.
    # Since the original mask was at [1:, 1:, 1:], we need to subtract 1 to get original voxel coordinates.
    # Actually wait. The cube_idx is generated by sliding over range(0, mask_tensor.shape+1).
    # In the original, the mask was placed at [:-1], and sliding was [0:mask.shape[0]].
    # Now, padded_mask is shape+2. We slide [0:mask.shape[0]+1].
    # So index 0 corresponds to the space BEFORE the original mask start.
    # Which corresponds to coordinate -1. Wait.
    # If the original mask is placed at index 1, the voxel center is at 1.
    # But marching cubes generates vertices within the cell [idx, idx+1].
    # So if we simply subtract 1 from the active_indices, we get the original relative coordinates.
    offsets = (torch.stack(active_indices, dim=-1).to(torch.float64) - 1.0)
    
    # Iterate over max 5 triangles
    for t in range(5):
        v1_idx = tri_data[:, t*3]
        valid_triangles = v1_idx >= 0
        
        if not valid_triangles.any():
            continue
        
        v1_i = v1_idx[valid_triangles]
        v2_i = tri_data[valid_triangles, t*3 + 1]
        v3_i = tri_data[valid_triangles, t*3 + 2]
        
        v1 = vertList_t[v1_i]
        v2 = vertList_t[v2_i]
        v3 = vertList_t[v3_i]
        
        off = offsets[valid_triangles]
        
        # Coordinates
        a = (v1 + off) * spacing_t
        b = (v2 + off) * spacing_t
        c = (v3 + off) * spacing_t
        
        # Area calculation: 0.5 * norm(cross_product(a-c, b-c))
        ab_area = torch.cross(a - c, b - c, dim=1)
        area = 0.5 * torch.norm(ab_area, dim=1)
        
        # volume calculation sum
        ab_vol = torch.cross(a, b, dim=1)
        vol = (ab_vol * c).sum(dim=1) * signs[valid_triangles]
        
        normals = 0.5 * torch.cross(b - a, c - a, dim=1)
        # wait, pyradiomics might not use the outward normal consistently?
        normals = normals * signs[valid_triangles].unsqueeze(1)
        area_vector_sum += normals.sum(dim=0)
        
        total_area += area.sum().item()
        total_volume += vol.sum().item()
        
        # Accumulate vertices to compute diameters later
        all_vertices_list.append(a)
        all_vertices_list.append(b)
        all_vertices_list.append(c)
        
    if len(all_vertices_list) > 0:
        all_vertices = torch.cat(all_vertices_list, dim=0)
        unique_vertices = torch.unique(all_vertices, dim=0)

        # Compute convex hull of vertices
        verts_np = unique_vertices.cpu().numpy()
        hull = ConvexHull(verts_np)
        hull_pts = torch.tensor(verts_np[hull.vertices], device=unique_vertices.device)

        # Max diameter of mesh is same as that of its convex hull
        max_3d_diameter = torch.cdist(hull_pts, hull_pts).max().item()

        # Iterate over z,x,y dims for max 2D diameters
        dims = [0,1,2]
        max_2d_diameters = [0.0, 0.0, 0.0]

        for i in dims:
            sl = unique_vertices[:, i]
            keep_dims = [j for j in dims if j != i]

            for s in torch.unique(sl):
                pts = unique_vertices[sl == s]

                # Calculate plane rank to determine collinearity of points
                pts_np = pts[:, keep_dims].cpu().numpy()
                centered = pts_np - pts_np.mean(axis=0)
                plane_rank = np.linalg.matrix_rank(centered)
                
                if plane_rank < 2:
                    # If points are colinear, calculate all pairwise distances
                    pts_t = torch.tensor(pts_np, device=pts.device)
                    d = torch.cdist(torch.tensor(pts_np), torch.tensor(pts_np))
                else:
                    # If plane slice is truly 2D, only calculate convex hull distances
                    hull = ConvexHull(pts_np)
                    hull_pts = torch.tensor(pts_np[hull.vertices], device=pts.device)
                    d = torch.cdist(hull_pts, hull_pts)
            
                max_2d_diameters[i] = max(max_2d_diameters[i], d.max().item())

        # Unpack 2D max diameters
        max_2d_slice, max_2d_col, max_2d_row = max_2d_diameters

    else:
        max_3d_diameter = 0.0
        max_2d_slice = 0.0
        max_2d_col = 0.0
        max_2d_row = 0.0

    return {
        "SurfaceArea": total_area,
        "MeshVolume": total_volume / 6.0,
        "Maximum3DDiameter": max_3d_diameter,
        "Maximum2DDiameterSlice": max_2d_slice,
        "Maximum2DDiameterColumn": max_2d_col,
        "Maximum2DDiameterRow": max_2d_row
    }
